---
- host: k3s
  become : true

  tasks:

  - name: Update system
    apt:
      update_cache: true

  - name: install k3s
    shell: curl -sfL https://get.k3s.io | sh -

  - name: Start k3s
    shell: sudo systemctl start k3s

  - name: Enable k3s
    shell: sudo systemctl enable k3s

  - name: Afficher le contenu du fichier
    ansible.builtin.cat:
      path: 